### PR TITLE
Update to latest tina deps, fix formify callback

### PR DESCRIPTION
**Pull request by jeffsee55**

### CODE REVIEW

**Comment by jamespohalloran** [comment]
Looks like this is correctly loading the post form instead of the global form by default. Although it seems now I can't edit the global form contextually anymore. Is that intended?

**Comment by jeffsee55** [comment]
You're not seeing it in the sidebar?
Screen Shot 2022-04-21 at 1 57 43 PM

**Comment by jamespohalloran** [comment]
> You're not seeing it in the sidebar?

Screen Shot 2022-04-21 at 7 15 32 PM

ok, so the bottom global form works with contextual editing (I didn't notice that one), but the "global" collection takes me to the "CMS"

**Comment by jeffsee55** [comment]
Yeah, that's currently how it works. I'm sure we can make it more clear

**Review by jamespohalloran — APPROVED** [review]

**Pull request merged**
