### PR TITLE
Basic Styles

### LINKED ISSUE #13: Add some styled blocks
Right now, the starter just renders the JSON of the blocks.
It would be nice to have some level of UI, even if it is very minimal
Screen Shot 2021-01-22 at 3 40 14 PM

### PR DESCRIPTION
**Pull request by spbyrne**
Just some basic page styling and components instead of displaying the raw data. 

Screen Shot 2021-02-11 at 3 14 44 PM

closes #13

### CODE REVIEW

**Comment by jamespohalloran** [comment]
Pumped about this! Having the JSON as a dropdown is a nice touch

**Comment by jeffsee55** [comment]
@spbyrne sorry I didn't even see this until just now! @jamespohalloran, @mitchmac - how do we want to move forward? Sounds like most testers wanted a little more styling.

@spbyrne  - this might need to be tweaked since we've cleaned out some things https://github.com/tinacms/tina-cloud-starter/pull/21

**Comment by spbyrne** [comment]
@jeffsee55 I'll take a look at the new changes and see about incorporating them into this PR.

**Comment by mitchmac** [comment]
@spbyrne I pulled this down and it feels great. I think it lines up with what folks might be expecting based on the feedback we've received. Anything else you're trying to do for this PR? If merged we can get this in front of users on next week!

**Comment by spbyrne** [comment]
No, I'm happy with this for now. I didn't want to get into the territory where it felt like this was meant to be used as-is to launch a website, but rather an example to break apart / change as needed.

**Review by jamespohalloran — APPROVED** [review]

**Pull request merged**
