### PR TITLE
Remove yarn dependency from scripts

### PR DESCRIPTION
**Pull request by jamespohalloran**
add note about changing scripts to use npm, for using npm vs yarn

- [ ] complete https://github.com/tinacms/tina-graphql-gateway/issues/113
- [ ] Remove scripts from package.json

### CODE REVIEW

**Review by jeffsee55 — COMMENTED** [review]
I don't think we even need `yarn` in there. So a better fix is probably to remove that from the scripts

**Review by DirtyF — APPROVED** [review]

**Comment by jamespohalloran** [comment]
@jeffsee55 When I remove them, I get errors like: `bash: watch:types: command not found`

**Comment by jeffsee55** [comment]
@jamespohalloran yeah the bash command needs to be replaced with a proper cli command, I think we were talking about adding `--watch-types` to the `server:start` command?

**Comment by jamespohalloran** [comment]
ohh ok gotcha, and yep removing yarn from the other commands works

**Pull request closed without merging**
