### PR TITLE
no media by default

### PR DESCRIPTION
**Pull request by logan-anderson**
This PR disables the media manager and the guide will show the user how to enable it if they wish.

### CODE REVIEW

**Comment by DirtyF** [comment]
@logan-anderson What's the motivation behind this change?

**Comment by logan-anderson** [comment]
@DirtyF Exactly. It works with this new section int he guide https://tina.io/guides/tina-cloud/starter/connect-to-tina-cloud/#media-management-optional

**Comment by DirtyF** [comment]
@logan-anderson too bad it adds a manual step, asking you to tweak the code and make media an option when it's one of the key feature added. I would have hoped we just tell people to configure a media store if credential are missing.

**Comment by mitchmac** [comment]
I think I feel similar to @DirtyF on this. The starter has both educational and demonstrative goals right now. With Forestry, a lot of folks use the starters to "kick the tires" before investing time in the product. Adding a coding step to kick the tires on a common CMS feature seems like too much friction.

Can we do anything conditionally based on the environment variables?

**Comment by jeffsee55** [comment]
I think we do have a reasonable error message right now. Though by not doing a dynamic import here it bloats the bundle size, we should at least import it dynamically

**Comment by jeffsee55** [comment]
After discussing we'll hold off on this change

**Pull request closed without merging**
