### PR TITLE
Lighthouse Score

### PR DESCRIPTION
**Pull request by logan-anderson**

### CODE REVIEW

**Comment by DirtyF** [comment]
👏 This is looking good!

CleanShot 2021-05-27 at 20 46 47@2x


Can't see where that Layout Shift is coming from in the Experience, did you spot it @logan-anderson  🤔

**Comment by logan-anderson** [comment]
@DirtyF I was already on it 😆  It should be fixed now 🤞

**Comment by spbyrne** [comment]
Nice work!

**Comment by DirtyF** [comment]
CleanShot 2021-05-27 at 21 34 17@2x

Great work Logan, remaining issues are related to styles (image ratio) and colour contrast and should be easily fixed.

**Comment by logan-anderson** [comment]
I think @spbyrne said that he would take a look at those issues when he got a chance.

**Comment by spbyrne** [comment]
I'm busy this morning but I took a look last night and have some contrast improvements I'll push up later; we can merge this as-is; it's a significant improvement!

**Review by DirtyF — APPROVED** [review]
On our way to the perfect lighthouse score! 🚀

**Pull request merged**
