### PR TITLE
add LICENSE

### LINKED ISSUE #76: Clarify license for this repo
Hi,

we are a holocratic organized software development company and are exploring the usage of tina cloud starter / tina cms as our main "cms engine" for our internal work aswell as the software we are writing for our clients. Unfortunately I have not found some license indication for the code found in this repo, could you kindly clarify if the starter is aswell released under the Apache-2.0 license?

Thanks!

Christoph

### PR DESCRIPTION
**Pull request by DirtyF**
fix #76

### CODE REVIEW

**Comment by jpatters** [comment]
Yes please!

**Comment by jpatters** [comment]
@DirtyF can you also add a `NOTICE` file to this? see https://www.apache.org/legal/src-headers.html#notice

**Comment by DirtyF** [comment]
@jpatters Something like that?

```
Tina Cloud Starter
Copyright 2021 Forestry.io

This product includes software developed at Forestry.io (http://www.forestry.io/).
```

**Comment by jpatters** [comment]
@DirtyF looks great. Thanks!

**Review by jpatters — APPROVED** [review]

**Pull request merged**
