### PR TITLE
Feat/admin page

### PR DESCRIPTION
**Pull request by logan-anderson**
Fixes: https://github.com/tinacms/tinacms/issues/2038

Demo: https://www.loom.com/share/c2a419efcf1745d8b70c9e3495e7375d

cc @scottgallant @spbyrne @jamespohalloran @perkinsjr  would love feedback.

### CODE REVIEW

**Review by perkinsjr — APPROVED** [review]

**Comment by perkinsjr** [comment]
LGTM - sorry I commented on the issue versus PR. Should help people understand when using cloud starter.

**Comment by spbyrne** [comment]
I'm just going to adjust a few styles on this PR.

**Comment by scottgallant** [comment]
This is great.  Thanks for the  quick loom video 👍 

Upon logging in, could we automatically redirect someone to a) the last page they were on, or b) fall back to the homepage?

**Comment by jeffsee55** [comment]
> Upon logging in, could we automatically redirect someone to a) the last page they were on, or b) fall back to the homepage?

We' can't detect the last page they were on programmatically (browsers won't allow it), this was the main reason for this PR in general, because the next best thing we can do is give the editor a better feel for where they are. They can select "Go back", but that's sort of on them to know if they were on a page that came from this site

**Comment by spbyrne** [comment]
I pushed a style update; works great for me. I think this is a good solution for now, we'll have to see what users think. I think the auto redirection stuff can get confusing.

**Comment by spbyrne** [comment]
Screen Shot 2021-08-17 at 3 34 56 PM
Screen Shot 2021-08-17 at 3 35 17 PM

**Comment by jamespohalloran** [comment]
Love it! I could see this admin page being used for more and more functionality in the future. Remembering a single "/admin" also feels more intuitive compared to individual pages like "/logout" 👍

**Pull request merged**
